### ISSUE TITLE
Nether Portals can not Generate

### ISSUE THREAD

**Issue by Jacob0225** [MC-datapack/Extended-World-Height#9]
I get this error and I am at spawn

[19:34:51] [Server thread/ERROR]: Unable to create a portal, likely target out of worldborder

**Comment by MC-datapack** [comment]
Are you using the newest version?

**Comment by Jacob0225** [comment]
No sorry It is fixed in newest version but now I can't get out of the nether (there is a bug report for it)

**Comment by Sovietsupporter69** [comment]
I can confirm this is still a problem on mod version 3.3, same error code too
